FROM alpine:latest

# Add some libs required by .NET runtime
RUN apk add --no-cache libstdc++ libintl icu

EXPOSE 80
EXPOSE 443

# Copy 
WORKDIR /app
COPY ./publish ./

ENTRYPOINT ["./Rashtan.AuditStory.API", "--urls", "http://0.0.0.0:80"]